name: Release Please
description: "Release please workflow with npm, git, pnpm, and pre-release scripts"
inputs:
  NPM_TOKEN:
    description: NPM Token
    required: false
  GITHUB_TOKEN:
    description: GitHub Personal Access Token
    required: false
  NPM_REGISTRY:
    description: "NPM Registry (default: '//registry.npmjs.org/')"
    required: false
  PUBLISH_SCRIPT:
    description: "Run an npm script instead of the default publish command: `pnpm publish --ignore-scripts`"
    required: false
  PRERELEASE_SCRIPTS:
    description: "package.json scripts to run before release. (default: 'build,lint,test,docs')"
    required: false
  NO_BAIL:
    description: "Don't bail on prerelease script failures [true/false] (default: false)"
    required: false
  BAIL_ON_MISSING:
    description: "Bail on missing prerelease script [true/false] (default: false)"
    required: false
  DRY_RUN:
    description: "Commands will be printed instead of executed. [true/false/publish-only] (default: false).
      If 'publish-only' is specified, all commands will run normally except for the 'publish' command, which will be run with the `--dry-run` flag."
    required: false
  DEBUG:
    description: "Prints debug information. [true/false] (default: false)"
    required: false
  CONFIG_ONLY:
    description: "Only verify configuration. [true/false] (default: false)"
    required: false
  PRERELEASE_ONLY:
    description: "ONLY run prerelease scripts. [true/false] (default: false)"
    required: false
  MONOREPO:
    description: "Monorepo mode. [true/false/auto] (default: auto) - By default, will automatically detect if the repo is a monorepo."
    required: false
  AUTOFIX_LOCKFILE:
    description: "Autofix lockfile. [true/false] (default: true)"
    required: false
  RELEASE_COMMAND:
    description: "Release Please Command. Single repos default to both, monorepos default to manifest. [github-release/release-pr/manifest/manifest-pr]"
    required: false
  AUTO_BOOTSTRAP:
    description: "Auto bootstrap new packages. [true/false] (default: false)"
    required: false
outputs:
  releases_created:
    description: Whether a release was created
    value: ${{ steps.release.outputs.releases_created }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ inputs.GITHUB_TOKEN }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7

    - name: Verify configuration & run prerelease scripts
      if: ${{ inputs.PRERELEASE_ONLY != 'true' }}
      id: prerelease
      run: ${{ github.action_path }}/src/config.sh '${{ toJSON(inputs) }}' '${{ github.repository }}'
      shell: bash

    - name: Setup Node.js
      if: ${{ steps.prerelease.outputs.should-release == 'true' }}
      uses: actions/setup-node@v3.5.1
      with:
        node-version: "lts/*"
        cache: pnpm

    - name: Run release script
      if: ${{ steps.prerelease.outputs.should-release == 'true' }}
      run: ${{ github.action_path }}/src/release.sh '${{ toJSON(inputs) }}' '${{ github.repository }}'
      shell: bash
